secret:
  name: events-stack-db # Name of the Kubernetes Secret containing DB_USER and DB_PASS keys for database credentials

config:
  DEBUG: "true"

  PORT: "8081"
            
  DB_HOST: pg-cluster-rw.krateo-system.svc.cluster.local
  DB_NAME: events-db
  DB_READY_TIMEOUT: "5m"
  DB_PARAMS: "sslmode=disable&connect_timeout=5"

  PM_MAX_PARTITIONS_SIZE: "1073741824" # 1GB
  PM_TRIGGER_RATIO: "0.75"
  PM_TARGET_RATIO: "0.60"
  PM_RETENTION_DAYS: "2"

  OTEL_ENABLED: "false"
  OTEL_EXPORT_INTERVAL: "30s"
