replicas: 1

config:
  DEBUG: "true"

  PORT: "8081"

  DB_HOST: postgres.eventstack-system.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: testdb
  DB_USER: test
  DB_PASS: test
  DB_PARAMS: "sslmode=disable"

  PM_MAX_PARTITIONS_SIZE: "1073741824" # 1GB
  PM_TRIGGER_RATIO: "0.75"
  PM_TARGET_RATIO: "0.60"
  PM_RETENTION_DAYS: "2"


service:
  port: 8081

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
